### ISSUE TITLE
Problem to execute run.py

### ISSUE THREAD

**Issue by rodrigoduartefis** [adammoss/supernovae#1]
Following the instructions, I tried to run:

$ python run.py -f test.ini

And it returns the error:

Using TensorFlow backend.
Reading dataset:  data/unblind_hostz_1.csv
Reading dataset:  data/unblind_hostz_2.csv
Reading dataset:  data/unblind_hostz_3.csv
Reading dataset:  data/unblind_hostz_4.csv
Reading dataset:  data/unblind_hostz_5.csv
Build model...
Traceback (most recent call last):
  File "run.py", line 61, in <module>
    consensus=consensus)
  File "/home/rodrigods/supernovae-master/train.py", line 197, in train
    model = build_model(nb_hidden, nb_classes, dropout, sequence_len, output_dim, bidirectional=bidirectional, rnn_type=rnn_type, activation=activation, consensus=consensus)
  File "/home/rodrigods/supernovae-master/train.py", line 90, in build_model
    z = MaskLambda(lambda_mask_average,output_shape=lambda shape: (shape[0],) + shape[2:])(z)
  File "/home/rodrigods/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/rodrigods/supernovae-master/custom_layers.py", line 61, in call
    return self.function(x, **arguments)
  File "/home/rodrigods/supernovae-master/custom_layers.py", line 125, in lambda_mask_average
    return K.batch_dot(x,mask,axes=1) / K.sum(mask, axis=-1, keepdims=True)
  File "/home/rodrigods/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1057, in batch_dot
    out = tf.matmul(x, y, adjoint_a=adj_x, adjoint_b=adj_y)
  File "/home/rodrigods/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1786, in matmul
    a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "/home/rodrigods/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 290, in _batch_mat_mul
    adj_y=adj_y, name=name)
  File "/home/rodrigods/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 526, in apply_op
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'BatchMatMul' Op has type bool that does not match type float32 of argument 'x'.

**Comment by tomcharnock** [comment]
Hi, this is a problem of the version of Keras you are using. This was written before the masked lambda layer was merged with the normal layer. I have recently written an update for this code so I'll try and push it as soon as possible so that it works with Keras 2.0. If you want to use it in the mean time you could use whichever version of Keras was live last August.

**Comment by rodrigoduartefis** [comment]
Thanks! It works!
